<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"/>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css"/>
  <script type="text/javascript">
      $(function(){
         $("#dob").datepicker(); 
      });
  </script>
  <script src="http://<?php echo ROOT_URL; ?>apps/frontend/public/js/validation.js" type="text/javascript"></script>
<h2 style="font-family:Arial;color:#333333;text-shadow: 1px 1px 2px #ccc;">Register at Fortune FX</h2>
<hr/>
<div id="reg_step">
        <ul>
            <li style="background:#0086b3;color:#fff;">1. Personal Details</li>
            <li>2. Account Credentials</li>
            <li>3. Funding Details</li>
            <li>4. Finish</li>
        </ul>
    <div style="width:0;height:0;border-left:10px solid transparent;border-right:10px solid transparent;border-top:10px solid #0086b3;position:relative;left:88px;"></div>
    </div>
<div class="form_panel">
    <span style="font-family:Arial;font-size:15px;color:#404040;">Please fill up the form below to register at Fortune FX.</span> <span style="color:#216C2A;font-family:Arial;font-size:15px;">* Required Field.</span><br/><br/>
    <h3 style="font-family:Arial;color:#333333;text-shadow: 0px 0px 1px #ccc;">Personal Details</h3>
    <hr/>
    <form method="post" action="" id="step1_form">
        <label for="title_salute"><span style="color:#216C2A;font-family:Arial;font-size:17px;">*</span>Title: </label><span id="title_msg" style="font-family:Arial;font-size:13px;color:#cc0000;"><?php echo form_individual_error("title_salute"); ?></span>
    <select id="title_salute" name="title_salute">
        <option value="Mr" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["title_salute"] == "Mr" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("title_salute", "Mr");} ?>>Mr</option>
        <option value="Mrs" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["title_salute"] == "Mrs" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("title_salute", "Mrs");} ?>>Mrs</option>
        <option value="Ms" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["title_salute"] == "Ms" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("title_salute", "Ms");} ?>>Ms</option>
    </select>
        <label for="first_name"><span style="color:#216C2A;font-family:Arial;font-size:17px;">*</span>Firstname: </label><span id="f_name_msg" style="font-family:Arial;font-size:13px;color:#cc0000;"><?php echo form_individual_error("first_name"); ?></span><input type="text" id="first_name" name="first_name" placeholder="Firstname" value="<?php if(isset($_SESSION["reg_step_1"]) && !isset($_POST["save_cont"])){echo $_SESSION["reg_step_1"]["first_name"];} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_value("first_name");} ?>"/>
    <label for="middle_name">Middlename: (Optional)</label><input type="text" id="middle_name" name="middle_name" placeholder="Middlename" value="<?php if(isset($_SESSION["reg_step_1"]) && !isset($_POST["save_cont"])){echo $_SESSION["reg_step_1"]["middle_name"];} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_value("middle_name");} ?>"/>
    <label for="last_name"><span style="color:#216C2A;font-family:Arial;font-size:17px;">*</span>Lastname: </label><span id="l_name_msg" style="font-family:Arial;font-size:13px;color:#cc0000;"><?php echo form_individual_error("last_name"); ?></span><input type="text" id="last_name" name="last_name" placeholder="Lastname" value="<?php if(isset($_SESSION["reg_step_1"]) && !isset($_POST["save_cont"])){echo $_SESSION["reg_step_1"]["last_name"];} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_value("last_name");} ?>"/>
    <label for="dob"><span style="color:#216C2A;font-family:Arial;font-size:17px;">*</span>Date Of Birth: </label><span id="dob_msg" style="font-family:Arial;font-size:13px;color:#cc0000;"><?php echo form_individual_error("dob"); ?></span><input type="text" id="dob" name="dob" placeholder="MM/DD/YYYY" value="<?php if(isset($_SESSION["reg_step_1"]) && !isset($_POST["save_cont"])){echo $_SESSION["reg_step_1"]["dob"];} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_value("dob");} ?>"/>
    <label for="phone"><span style="color:#216C2A;font-family:Arial;font-size:17px;">*</span>Phone: </label><span id="phn_msg" style="font-family:Arial;font-size:13px;color:#cc0000;"><?php echo form_individual_error("phone"); ?></span><input type="text" id="phone" name="phone" placeholder="Phone" value="<?php if(isset($_SESSION["reg_step_1"]) && !isset($_POST["save_cont"])){echo $_SESSION["reg_step_1"]["phone"];} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_value("phone");} ?>"/>
    <label for="country"><span style="color:#216C2A;font-family:Arial;font-size:17px;">*</span>Country: </label>
    <span id="country_msg" style="font-family:Arial;font-size:13px;color:#cc0000;"><?php echo form_individual_error("country"); ?></span>
    <select id="country" name="country">
        <option value="">Select Your Country</option>
<option value="Afghanistan" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Afghanistan" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Afghanistan");} ?>>Afghanistan</option>
<option value="Albania" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Albania" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Albania");} ?>>Albania</option>
<option value="Algeria" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Algeria" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Algeria");} ?>>Algeria</option>
<option value="American Samoa" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "American Samoa" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "American Samoa");} ?>>American Samoa</option>
<option value="Andorra" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Andorra" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Andorra");} ?>>Andorra</option>
<option value="Angola" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Angola" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Angola");} ?>>Angola</option>
<option value="Anguilla" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Anguilla" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Anguilla");} ?>>Anguilla</option>
<option value="Antarctica" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Antarctica" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Antarctica");} ?>>Antarctica</option>
<option value="Antigua" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Antigua" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Antigua And Barbuda");} ?>>Antigua And Barbuda</option>
<option value="Argentina" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Argentina" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Argentina");} ?>>Argentina</option>
<option value="Armenia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Armenia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Armenia");} ?>>Armenia</option>
<option value="Aruba" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Aruba" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Aruba");} ?>>Aruba</option>
<option value="Australia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Australia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Australia");} ?>>Australia</option>
<option value="Austria" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Austria" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Austria");} ?>>Austria</option>
<option value="Azerbaijan" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Azerbaijan" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Azerbaijan");} ?>>Azerbaijan</option>
<option value="Bahamas" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Bahamas" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Bahamas");} ?>>Bahamas</option>
<option value="Bahrain" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Bahrain" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Bahrain");} ?>>Bahrain</option>
<option value="Bangladesh" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Bangladesh" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Bangladesh");} ?>>Bangladesh</option>
<option value="Barbados" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Barbados" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Barbados");} ?>>Barbados</option>
<option value="Belarus" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Belarus" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Belarus");} ?>>Belarus</option>
<option value="Belgium" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Belgium" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Belgium");} ?>>Belgium</option>
<option value="Belize" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Belize" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Belize");} ?>>Belize</option>
<option value="Benin" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Benin" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Benin");} ?>>Benin</option>
<option value="Bermuda" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Bermuda" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Bermuda");} ?>>Bermuda</option>
<option value="Bhutan" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Bhutan" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Bhutan");} ?>>Bhutan</option>
<option value="Bolivia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Bolivia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Bolivia");} ?>>Bolivia</option>
<option value="Bosnia And Herzegowina" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Bosnia And Herzegowina" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Bosnia And Herzegowina");} ?>>Bosnia And Herzegowina</option>
<option value="Botswana" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Botswana" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Botswana");} ?>>Botswana</option>
<option value="Bouvet Island" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Bouvet Island" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Bouvet Island");} ?>>Bouvet Island</option>
<option value="Brazil" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Brazil" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Brazil");} ?>>Brazil</option>
<option value="British Indian Ocean Territory" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "British Indian Ocean Territory" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "British Indian Ocean Territory");} ?>>British Indian Ocean Territory</option>
<option value="Brunei Darussalam" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Bruei Darussalam" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Brunei Darussalam");} ?>>Brunei Darussalam</option>
<option value="Bulgaria" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Bulgaria" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Bulgaria");} ?>>Bulgaria</option>
<option value="Burkina Faso" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Burkina Faso" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Burkina Faso");} ?>>Burkina Faso</option>
<option value="Burundi" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Burundi" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Burundi");} ?>>Burundi</option>
<option value="Cambodia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Cambodia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Cambodia");} ?>>Cambodia</option>
<option value="Cameroon" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Cameroon" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Cameroon");} ?>>Cameroon</option>
<option value="Canada" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Canada" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Canada");} ?>>Canada</option>
<option value="Cape Verde" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Cape Verde" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Cape Verde");} ?>>Cape Verde</option>
<option value="Cayman Islands" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Cayman Islands" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Cayman Islands");} ?>>Cayman Islands</option>
<option value="Central African Republic" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Central African Republic" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Central African Republic");} ?>>Central African Republic</option>
<option value="Chad" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Chad" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Chad");} ?>>Chad</option>
<option value="Chile" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Chile" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Chile");} ?>>Chile</option>
<option value="China" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "China" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "China");} ?>>China</option>
<option value="Christmas Island" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Christmas Island" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Christmas Island");} ?>>Christmas Island</option>
<option value="Cocos (Keeling) Islands" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Cocos (Keeling) Islands" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Cocos (Keeling) Islands");} ?>>Cocos (Keeling) Islands</option>
<option value="Colombia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Colombia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Colombia");} ?>>Colombia</option>
<option value="Comoros" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Comoros" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Comoros");} ?>>Comoros</option>
<option value="Congo" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Congo" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Congo");} ?>>Congo</option>
<option value="Cook Islands" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Cook Islands" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Cook Islands");} ?>>Cook Islands</option>
<option value="Costa Rica" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Costa Rica" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Costa Rica");} ?>>Costa Rica</option>
<option value="Cote D'Ivoire" <?php echo set_select("country", "Cote D'Ivoire");?>>Cote D'Ivoire</option>
<option value="Croatia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Croatia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Croatia");} ?>>Croatia</option>
<option value="Cuba" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Cuba" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Cuba");} ?>>Cuba</option>
<option value="Cyprus" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Cyprus" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Cyprus");} ?>>Cyprus</option>
<option value="Czech Republic" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Czech Republic" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Czech Republic");} ?>>Czech Republic</option>
<option value="Denmark" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Denmark" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Denmark");} ?>>Denmark</option>
<option value="Djibouti" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Djibouti" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Djibouti");} ?>>Djibouti</option>
<option value="Dominica" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Dominica" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Dominica");} ?>>Dominica</option>
<option value="Dominican Republic" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Dominican Republic" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Dominican Republic");} ?>>Dominican Republic</option>
<option value="East Timor" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "East Timor" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "East Timor");} ?>>East Timor</option>
<option value="Ecuador" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Ecuador" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Ecuador");} ?>>Ecuador</option>
<option value="Egypt" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Egypt" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Egypt");} ?>>Egypt</option>
<option value="El Salvador" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "El Salvador" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "El Salvador");} ?>>El Salvador</option>
<option value="Equatorial Guinea" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Equatorial Guinea" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Equatorial Guinea");} ?>>Equatorial Guinea</option>
<option value="Eritrea" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Eritrea" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Eritrea");} ?>>Eritrea</option>
<option value="Estonia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Estonia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Estonia");} ?>>Estonia</option>
<option value="Ethiopia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Ethiopia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Ethiopia");} ?>>Ethiopia</option>
<option value="Falkland Islands (Malvinas)" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Falkland Islands (Malvinas)" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Falkland Islands (Malvinas)");} ?>>Falkland Islands (Malvinas)</option>
<option value="Faroe Islands" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Faroe Islands" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Faroe Islands");} ?>>Faroe Islands</option>
<option value="Fiji" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Fiji" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Fiji");} ?>>Fiji</option>
<option value="Finland" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Finland" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Finland");} ?>>Finland</option>
<option value="France" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "France" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "France");} ?>>France</option>
<option value="French Guiana" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "French Guiana" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "French Guiana");} ?>>French Guiana</option>
<option value="French Polynesia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "French Polynesia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "French Polynesia");} ?>>French Polynesia</option>
<option value="French Southern Territories" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "French Southern Territories" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "French Southern Territories");} ?>>French Southern Territories</option>
<option value="Gabon" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Gabon" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Gabon");} ?>>Gabon</option>
<option value="Gambia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Gambia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Gambia");} ?>>Gambia</option>
<option value="Georgia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Georgia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Georgia");} ?>>Georgia</option>
<option value="Germany" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Germany" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Germany");} ?>>Germany</option>
<option value="Ghana" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Ghana" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Ghana");} ?>>Ghana</option>
<option value="Gibraltar" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Gibraltar" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Gibraltar");} ?>>Gibraltar</option>
<option value="Greece" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Greece" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Greece");} ?>>Greece</option>
<option value="Greenland" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Greenland" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Greenland");} ?>>Greenland</option>
<option value="Grenada" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Grenada" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Grenada");} ?>>Grenada</option>
<option value="Guadeloupe" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Guadeloupe" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Guadeloupe");} ?>>Guadeloupe</option>
<option value="Guam" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Guam" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Guam");} ?>>Guam</option>
<option value="Guatemala" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Guatemala" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Guatemala");} ?>>Guatemala</option>
<option value="Guinea" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Guinea" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Guinea");} ?>>Guinea</option>
<option value="Guinea-Bissau" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Guinea-Bissau" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Guinea-Bissau");} ?>>Guinea-Bissau</option>
<option value="Guyana" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Guyana" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Guyana");} ?>>Guyana</option>
<option value="Haiti" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Haiti" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Haiti");} ?>>Haiti</option>
<option value="Heard And Mc Donald Islands" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Heard And Mc Donald Islands" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Heard And Mc Donald Islands");} ?>>Heard And Mc Donald Islands</option>
<option value="Holy See (Vatican City State)" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Holy See (Vatican City State)" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Holy See (Vatican City State)");} ?>>Holy See (Vatican City State)</option>
<option value="Honduras" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Honduras" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Honduras");} ?>>Honduras</option>
<option value="Hong Kong" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Hong Kong" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Hong Kong");} ?>>Hong Kong</option>
<option value="Hungary" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Hungary" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Hungary");} ?>>Hungary</option>
<option value="Iceland" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Iceland" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Iceland");} ?>>Iceland</option>
<option value="India" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "India" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "India");} ?>>India</option>
<option value="Indonesia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Indonesia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Indonesia");} ?>>Indonesia</option>
<option value="Iran" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Iran" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Iran");} ?>>Iran</option>
<option value="Iraq" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Iraq" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Iraq");} ?>>Iraq</option>
<option value="Ireland" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Ireland" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Ireland");} ?>>Ireland</option>
<option value="Israel" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Israel" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Israel");} ?>>Israel</option>
<option value="Italy" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Italy" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Italy");} ?>>Italy</option>
<option value="Jamaica" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Jamaica" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Jamaica");} ?>>Jamaica</option>
<option value="Japan" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Japan" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Japan");} ?>>Japan</option>
<option value="Jordan" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Jordan" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Jordan");} ?>>Jordan</option>
<option value="Kazakhstan" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Kazakhstan" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Kazakhstan");} ?>>Kazakhstan</option>
<option value="Kenya" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Kenya" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Kenya");} ?>>Kenya</option>
<option value="Kiribati" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Kiribati" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Kiribati");} ?>>Kiribati</option>
<option value="Korea, Democratic People's Republic" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Korea Democratice People's Republicc" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Korea, Democratic People's Republic");} ?>>Korea, Democratic People's Republic</option>
<option value="Korea, Republic Of" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Korea, Republic Of" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Korea, Republic Of");} ?>>Korea, Republic Of</option>
<option value="Kuwait" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Kuwait" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Kuwait");} ?>>Kuwait</option>
<option value="Kyrgyzstan" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Kyrgyzstan" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Kyrgyzstan");} ?>>Kyrgyzstan</option>
<option value="Lao People's Dem Republic" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Lao People's Dem Republic" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Lao People's Dem Republic");} ?>>Lao People's Dem Republic</option>
<option value="Latvia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Latvia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Latvia");} ?>>Latvia</option>
<option value="Lebanon" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Lebanon" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Lebanon");} ?>>Lebanon</option>
<option value="Lesotho" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Lesotho" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Lesotho");} ?>>Lesotho</option>
<option value="Liberia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Liberia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Liberia");} ?>>Liberia</option>
<option value="Libyan Arab Jamahiriya" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Libyan Arab Jamahiriya" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Libyan Arab Jamahiriya");} ?>>Libyan Arab Jamahiriya</option>
<option value="Liechtenstein" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Liechtenstein" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Liechtenstein");} ?>>Liechtenstein</option>
<option value="Lithuania" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Lithuania" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Lithuania");} ?>>Lithuania</option>
<option value="Luxembourg" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Luxembourg" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Luxembourg");} ?>>Luxembourg</option>
<option value="Macau" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Macau" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Macau");} ?>>Macau</option>
<option value="Macedonia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Macedonia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Macedonia");} ?>>Macedonia</option>
<option value="Madagascar" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Madagascar" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Madagascar");} ?>>Madagascar</option>
<option value="Malawi" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Malawi" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Malawi");} ?>>Malawi</option>
<option value="Malaysia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Malaysia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Malaysia");} ?>>Malaysia</option>
<option value="Maldives" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Maldives" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Maldives");} ?>>Maldives</option>
<option value="Mali" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Mali" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Mali");} ?>>Mali</option>
<option value="Malta" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Malta" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Malta");} ?>>Malta</option>
<option value="Marshall Islands" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Marshall Islands" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Marshall Islands");} ?>>Marshall Islands</option>
<option value="Martinique" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Martinique" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Martinique");} ?>>Martinique</option>
<option value="Mauritania" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Mauritania" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Mauritania");} ?>>Mauritania</option>
<option value="Mauritius" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Mauritius" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Mauritius");} ?>>Mauritius</option>
<option value="Mayotte" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Mayotte" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Mayotte");} ?>>Mayotte</option>
<option value="Mexico" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Mexico" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Mexico");} ?>>Mexico</option>
<option value="Micronesia, Federated States" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Micronesia, Federated States" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Micronesia, Federated States");} ?>>Micronesia, Federated States</option>
<option value="Moldova, Republic Of" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Moldova, Republic Of" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Moldova, Republic Of");} ?>>Moldova, Republic Of</option>
<option value="Monaco" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Monaco" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Monaco");} ?>>Monaco</option>
<option value="Mongolia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Mongolia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Mongolia");} ?>>Mongolia</option>
<option value="Montserrat" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Montserrat" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Montserrat");} ?>>Montserrat</option>
<option value="Morocco" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Morocco" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Morocco");} ?>>Morocco</option>
<option value="Mozambique" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Mozambique" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Mozambique");} ?>>Mozambique</option>
<option value="Myanmar" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Myanmar" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Myanmar");} ?>>Myanmar</option>
<option value="Namibia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Namibia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Namibia");} ?>>Namibia</option>
<option value="Nauru" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Nauru" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Nauru");} ?>>Nauru</option>
<option value="Nepal" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Nepal" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Nepal");} ?>>Nepal</option>
<option value="Netherlands" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Netherlands" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Netherlands");} ?>>Netherlands</option>
<option value="Netherlands Ant Illes" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Netherlands Ant Illes" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Netherlands Ant Illes");} ?>>Netherlands Ant Illes</option>
<option value="New Caledonia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "New Caledonia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "New Caledonia");} ?>>New Caledonia</option>
<option value="New Zealand" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "New Zealand" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "New Zealand");} ?>>New Zealand</option>
<option value="Nicaragua" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Nicaragua" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Nicaragua");} ?>>Nicaragua</option>
<option value="Niger" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Niger" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Niger");} ?>>Niger</option>
<option value="Nigeria" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Nigeria" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Nigeria");} ?>>Nigeria</option>
<option value="Niue" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Niue" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Niue");} ?>>Niue</option>
<option value="Norfolk Island" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Norfolk Island" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Norfolk Island");} ?>>Norfolk Island</option>
<option value="Northern Mariana Islands" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Northern Mariana Islands" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Northern Mariana Islands");} ?>>Northern Mariana Islands</option>
<option value="Norway" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Norway" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Norway");} ?>>Norway</option>
<option value="Oman" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Oman" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Oman");} ?>>Oman</option>
<option value="Pakistan" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Pakistan" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Pakistan");} ?>>Pakistan</option>
<option value="Palau" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Palau" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Palau");} ?>>Palau</option>
<option value="Panama" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Panama" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Panama");} ?>>Panama</option>
<option value="Papua New Guinea" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Papua New Guinea" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Papua New Guinea");} ?>>Papua New Guinea</option>
<option value="Paraguay" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Paraguay" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Paraguay");} ?>>Paraguay</option>
<option value="Peru" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Peru" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Peru");} ?>>Peru</option>
<option value="Philippines" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Philippines" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Philippines");} ?>>Philippines</option>
<option value="Pitcairn" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Pitcairn" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Pitcairn");} ?>>Pitcairn</option>
<option value="Poland" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Poland" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Poland");} ?>>Poland</option>
<option value="Portugal" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Portugal" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Portugal");} ?>>Portugal</option>
<option value="Puerto Rico" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Puerto Rico" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Puerto Rico");} ?>>Puerto Rico</option>
<option value="Qatar" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Qatar" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Qatar");} ?>>Qatar</option>
<option value="Reunion" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Reunion" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Reunion");} ?>>Reunion</option>
<option value="Romania" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Romania" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Romania");} ?>>Romania</option>
<option value="Russian Federation" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Russian Federation" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Russian Federation");} ?>>Russian Federation</option>
<option value="Rwanda" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Rwanda" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Rwanda");} ?>>Rwanda</option>
<option value="Saint K Itts And Nevis" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Saint K Itts And Nevis" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Saint K Itts And Nevis");} ?>>Saint K Itts And Nevis</option>
<option value="Saint Lucia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Saint Lucia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Saint Lucia");} ?>>Saint Lucia</option>
<option value="Saint Vincent, The Grenadines" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Saint Vincent, The Grenadines" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Saint Vincent, The Grenadines");} ?>>Saint Vincent, The Grenadines</option>
<option value="Samoa" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Samoa" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Samoa");} ?>>Samoa</option>
<option value="San Marino" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "San Marino" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "San Marino");} ?>>San Marino</option>
<option value="Sao Tome And Principe" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Sao Tome And Principe" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Sao Tome And Principe");} ?>>Sao Tome And Principe</option>
<option value="Saudi Arabia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Saudi Arabia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Saudi Arabia");} ?>>Saudi Arabia</option>
<option value="Senegal" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Senegal" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Senegal");} ?>>Senegal</option>
<option value="Seychelles" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Seychelles" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Seychelles");} ?>>Seychelles</option>
<option value="Sierra Leone" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Sierra Leone" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Sierra Leone");} ?>>Sierra Leone</option>
<option value="Singapore" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Singapore" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Singapore");} ?>>Singapore</option>
<option value="Slovakia (Slovak Republic)" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Slovakia (Slovak Republic)" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Slovakia (Slovak Republic)");} ?>>Slovakia (Slovak Republic)</option>
<option value="Slovenia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Slovenia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Slovenia");} ?>>Slovenia</option>
<option value="Solomon Islands" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Solomon Islands" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Solomon Islands");} ?>>Solomon Islands</option>
<option value="Somalia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Somalia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Somalia");} ?>>Somalia</option>
<option value="South Africa" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "South Africa" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "South Africa");} ?>>South Africa</option>
<option value="South Georgia , S Sandwich Is." <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "South Georgia , S Sandwich Is." && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "South Georgia , S Sandwich Is.");} ?>>South Georgia , S Sandwich Is.</option>
<option value="Spain" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Spain" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Spain");} ?>>Spain</option>
<option value="Sri Lanka" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Afghanistan" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Sri Lanka");} ?>>Sri Lanka</option>
<option value="St. Helena" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "St. Helena" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "St. Helena");} ?>>St. Helena</option>
<option value="St. Pierre And Miquelon" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Afghanistan" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "St. Pierre And Miquelon");} ?>>St. Pierre And Miquelon</option>
<option value="Sudan" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Sudan" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Sudan");} ?>>Sudan</option>
<option value="Suriname" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Suriname" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Suriname");} ?>>Suriname</option>
<option value="Svalbard, Jan Mayen Islands" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Svalbard, Jan Mayen Islands" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Svalbard, Jan Mayen Islands");} ?>>Svalbard, Jan Mayen Islands</option>
<option value="Sw Aziland" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Sw Aziland" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Sw Aziland");} ?>>Sw Aziland</option>
<option value="Sweden" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Sweden" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Sweden");} ?>>Sweden</option>
<option value="Switzerland" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Switzerland" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Switzerland");} ?>>Switzerland</option>
<option value="Syrian Arab Republic" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Syrian Arab Republic" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Syrian Arab Republic");} ?>>Syrian Arab Republic</option>
<option value="Taiwan" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Taiwan" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Taiwan");} ?>>Taiwan</option>
<option value="Tajikistan" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Tajikistan" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Tajikistan");} ?>>Tajikistan</option>
<option value="Tanzania, United Republic Of" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Tanzania, United Republic Of" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Tanzania, United Republic Of");} ?>>Tanzania, United Republic Of</option>
<option value="Thailand" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Thailand" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Thailand");} ?>>Thailand</option>
<option value="Togo" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Togo" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Togo");} ?>>Togo</option>
<option value="Tokelau" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Tokelau" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Tokelau");} ?>>Tokelau</option>
<option value="Tonga" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Tonga" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Tonga");} ?>>Tonga</option>
<option value="Trinidad And Tobago" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Trinidad And Tobago" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Trinidad And Tobago");} ?>>Trinidad And Tobago</option>
<option value="Tunisia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Tunisia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Tunisia");} ?>>Tunisia</option>
<option value="Turkey" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Turkey" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Turkey");} ?>>Turkey</option>
<option value="Turkmenistan" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Turkmenistan" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Turkmenistan");} ?>>Turkmenistan</option>
<option value="Turks And Caicos Islands" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Turks And Caiso Islands" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Turks And Caicos Islands");} ?>>Turks And Caicos Islands</option>
<option value="Tuvalu" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Tuvalu" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Tuvalu");} ?>>Tuvalu</option>
<option value="Uganda" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Uganda" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Uganda");} ?>>Uganda</option>
<option value="Ukraine" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Ukraine" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Ukraine");} ?>>Ukraine</option>
<option value="United Arab Emirates" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "United Arab Emirates" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "United Arab Emirates");} ?>>United Arab Emirates</option>
<option value="United Kingdom" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "United Kingdom" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "United Kingdom");} ?>>United Kingdom</option>
<option value="United States" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "United States" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "United States");} ?>>United States</option>
<option value="United States Minor Is." <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "United States Minor Is." && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "United States Minor Is.");} ?>>United States Minor Is.</option>
<option value="Uruguay" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Uruguay" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Uruguay");} ?>>Uruguay</option>
<option value="Uzbekistan" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Uzbekistan" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Uzbekistan");} ?>>>Uzbekistan</option>
<option value="Vanuatu" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Vanuatu" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Vanuatu");} ?>>Vanuatu</option>
<option value="Venezuela" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Venezuela" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Venezuela");} ?>>Venezuela</option>
<option value="Vietnam" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Vietnam" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Vietnam");} ?>>Vietnam</option>
<option value="Virgin Islands (British)" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Virgin Islands (British)" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Virgin Islands (British)");} ?>>Virgin Islands (British)</option>
<option value="Virgin Islands (U.S.)" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Virgin Islands (U.S.)" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Virgin Islands (U.S.)");} ?>>Virgin Islands (U.S.)</option>
<option value="Wallis And Futuna Islands" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Wallis And Futuna Islands" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Wallis And Futuna Islands");} ?>>Wallis And Futuna Islands</option>
<option value="Western Sahara" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Western Sahara" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Western Sahara");} ?>>Western Sahara</option>
<option value="Yemen" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Yemen" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Yemen");} ?>>Yemen</option>
<option value="Zaire" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Zaire" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Zaire");} ?>>Zaire</option>
<option value="Zambia" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Zambia" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Zambia");} ?>>Zambia</option>
<option value="Zimbabwe" <?php if(isset($_SESSION["reg_step_1"]) && $_SESSION["reg_step_1"]["country"] == "Zimbabwe" && !isset($_POST["save_cont"])){echo "selected";} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_select("country", "Zimbabwe");} ?>>Zimbabwe</option>
    </select>
    <label for="add1"><span style="color:#216C2A;font-family:Arial;font-size:17px;">*</span>Address Line 1: </label><span id="add1_msg" style="font-family:Arial;font-size:13px;color:#cc0000;"><?php echo form_individual_error("add1"); ?></span><input type="text" id="add1" name="add1" placeholder="Address Line 1" value="<?php if(isset($_SESSION["reg_step_1"]) && !isset($_POST["save_cont"])){echo $_SESSION["reg_step_1"]["add1"];} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_value("add1");} ?>"/>
    <label for="add2">Address Line 2: (Optional) </label><input type="text" id="add2" name="add2" placeholder="Address Line 2" value="<?php if(isset($_SESSION["reg_step_1"]) && !isset($_POST["save_cont"])){echo $_SESSION["reg_step_1"]["add2"];} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_value("add2");} ?>"/>
    <label for="state"><span style="color:#216C2A;font-family:Arial;font-size:17px;">*</span>State: </label><span id="state_msg" style="font-family:Arial;font-size:13px;color:#cc0000;"><?php echo form_individual_error("state"); ?></span><input type="text" id="state" name="state" placeholder="State" value="<?php if(isset($_SESSION["reg_step_1"]) && !isset($_POST["save_cont"])){echo $_SESSION["reg_step_1"]["state"];} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_value("state");} ?>"/>
    <label for="suburb"><span style="color:#216C2A;font-family:Arial;font-size:17px;">*</span>Suburb: </label><span id="suburb_msg" style="font-family:Arial;font-size:13px;color:#cc0000;"><?php echo form_individual_error("suburb"); ?></span><input type="text" id="suburb" name="suburb" placeholder="Suburb" value="<?php if(isset($_SESSION["reg_step_1"]) && !isset($_POST["save_cont"])){echo $_SESSION["reg_step_1"]["suburb"];} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_value("suburb");} ?>"/>
    <label for="postcode"><span style="color:#216C2A;font-family:Arial;font-size:17px;">*</span>Postcode: </label><span id="postcode_msg" style="font-family:Arial;font-size:13px;color:#cc0000;"><?php echo form_individual_error("postcode"); ?></span><input type="text" id="postcode" name="postcode" placeholder="Postcode" value="<?php if(isset($_SESSION["reg_step_1"]) && !isset($_POST["save_cont"])){echo $_SESSION["reg_step_1"]["postcode"];} if((isset($_SESSION["reg_step_1"]) || !isset($_SESSION["reg_step_1"])) && isset($_POST["save_cont"])){echo set_value("postcode");} ?>"/>
    <label for="currency"><span style="color:#216C2A;font-family:Arial;font-size:17px;">*</span>Base Currency: </label>
    <select id="currency" name="currency">
        <option value="AUD">AUD</option>
    </select>
    <input type="submit" id="save_cont" name="save_cont" value="Save and Continue"/>
    </form>
    <span id="step_msg"></span>
</div>           